apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-web
  namespace: nolly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-web
  template:
    metadata:
      labels:
        app: target-web
    spec:
      containers:
        - name: web
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: target-web
  namespace: nolly
spec:
  selector:
    app: target-web
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP